name = "sample-todo"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "todo-api"
database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[observability]
enabled = true